#

application:
  namespace: smarter
  appName: smarter-dns
  configMapCoreName: smarter-dns-core
  configMapConfigName: smarter-dns-config

image:
  repository: ghcr.io/smarter-project/smarter-dns
  # @default -- chart.appVersion
  tag: ""
  pullPolicy: IfNotPresent

configuration:
  nodeSelector:
    smarter-dns: enabled
